/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>

#define RCC_Base 0x40023800U
#define RCC_AHB1ENR (*(volatile uint32_t*)(RCC_Base + 0x30))
#define GPIOB_BASE 0x40020400U

#define GPIOB_MODER (*(volatile uint32_t*)(GPIOB_BASE+0x00))
#define GPIOB_BSRR (*(volatile uint32_t*)(GPIOB_BASE + 0x18U))
int main(void){
	RCC_AHB1ENR |= (1<<1);
	GPIOB_MODER &= ~((3<<28)|(3<<14)|(3<<0));
	GPIOB_MODER |= ((1<<28) | (1<<14) | (1<<0));
	GPIOB_BSRR = ((1<<14) | (1<<7) | (1<<0));
	while(1){

	}
}
